version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        HONO_APP_PORT: ${HONO_APP_PORT}
    container_name: hanoi-api
    ports:
      - ${HONO_APP_PORT}:${HONO_APP_PORT}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:${HONO_APP_PORT}/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
