version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hanoi-api
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3000/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
